In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
vector = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
matrix = np.random.randint(1, 11, size=(5, 5))
print(matrix)

[[10  3  4 10  7]
 [ 1 10  3  1 10]
 [ 9  5  1  4  4]
 [ 9  9  2  1  5]
 [ 2  8  8  8  4]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
matrix = np.random.rand(4, 4)
print(matrix)

[[0.98993497 0.27354746 0.66773316 0.23096816]
 [0.54609635 0.27725337 0.62782884 0.63924957]
 [0.92143253 0.32755572 0.20156307 0.05425161]
 [0.53836565 0.54642721 0.48939017 0.39946379]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
array1 = np.random.randint(1, 11, size=5)
print("array1:", array1)

array2 = np.random.randint(1, 11, size=5)
print("array2:", array2)

addition = array1 + array2
print("addition:", addition)

subtraction = array1 - array2
print("subtraction:", subtraction)

multiplication = array1 * array2
print("multiplication:", multiplication)

array1: [9 5 2 4 5]
array2: [ 4  2  6 10 10]
addition: [13  7  8 14 15]
subtraction: [ 5  3 -4 -6 -5]
multiplication: [36 10 12 40 50]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
print("vector1:", vector1)

vector2 = np.array([7, 6, 5, 4, 3, 2, 1])
print("vector2:", vector2)

result = np.dot(vector1, vector2)
print("result:", result)

vector1: [1 2 3 4 5 6 7]
vector2: [7 6 5 4 3 2 1]
result: 84


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
print("matrix1:")
print(matrix1)

matrix2 = np.random.randint(1, 11, size=(2, 3))
print("matrix2:")
print(matrix2)

result = np.dot(matrix1, matrix2)
print("result:")
print(result)

matrix1:
[[2 7]
 [6 6]]
matrix2:
[[7 5 8]
 [5 6 9]]
result:
[[ 49  52  79]
 [ 72  66 102]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
matrix = np.random.randint(1, 11, size=(3, 3))
print("matrix:")
print(matrix)

inverse_matrix = np.linalg.inv(matrix)
print("inverse_matrix:")
print(inverse_matrix)

matrix:
[[3 5 5]
 [2 1 2]
 [2 7 2]]
inverse_matrix:
[[-0.5         1.04166667  0.20833333]
 [ 0.         -0.16666667  0.16666667]
 [ 0.5        -0.45833333 -0.29166667]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
matrix = np.random.rand(4, 4)
print("matrix:")
print(matrix)

transposed_matrix = np.transpose(matrix)
# transposed_matrix = matrix.T
print("transposed_matrix:")
print(transposed_matrix)

matrix:
[[0.73443886 0.18518665 0.89466759 0.30927246]
 [0.9606474  0.63046182 0.35400919 0.90269944]
 [0.91278706 0.36298835 0.23657473 0.49457406]
 [0.28570102 0.5474606  0.82960954 0.84876673]]
transposed_matrix:
[[0.73443886 0.9606474  0.91278706 0.28570102]
 [0.18518665 0.63046182 0.36298835 0.5474606 ]
 [0.89466759 0.35400919 0.23657473 0.82960954]
 [0.30927246 0.90269944 0.49457406 0.84876673]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
matrix = np.random.randint(1, 11, size=(3, 4))
print("matrix:")
print(matrix)

vector = np.random.randint(1, 11, size=4)
print("vector:")
print(vector)

result = np.dot(matrix, vector)
print("result:")
print(result)

matrix:
[[1 4 6 2]
 [7 6 8 3]
 [5 9 3 9]]
vector:
[4 2 6 7]
result:
[ 62 109 119]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
matrix = np.random.rand(2, 3)
print("matrix:")
print(matrix)

vector = np.random.rand(3)
print("vector:")
print(vector)

result = np.dot(matrix, vector)
print("result:")
print(result)

matrix:
[[0.68503756 0.79759818 0.40052203]
 [0.16086001 0.39718864 0.49948786]]
vector:
[0.89385944 0.32311252 0.51929072]
result:
[1.07802862 0.53150227]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
print("matrix1:")
print(matrix1)

matrix2 = np.random.randint(1, 11, size=(2, 2))
print("matrix2:")
print(matrix2)

result = matrix1 * matrix2
print("result:")
print(result)

matrix1:
[[ 5  2]
 [10  6]]
matrix2:
[[ 2  2]
 [10  6]]
result:
[[ 10   4]
 [100  36]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
print("matrix1:")
print(matrix1)

matrix2 = np.random.randint(1, 11, size=(2, 2))
print("matrix2:")
print(matrix2)

result = np.dot(matrix1, matrix2)
print("result:")
print(result)

matrix1:
[[3 6]
 [2 9]]
matrix2:
[[1 6]
 [1 4]]
result:
[[ 9 42]
 [11 48]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
matrix = np.random.randint(1, 101, size=(5, 5))
print("matrix:")
print(matrix)

result = np.sum(matrix)
print("result:")
print(result)

matrix:
[[46 73 81 25  8]
 [56 70 64 22 42]
 [69 99 48 79 12]
 [ 9 31 18 90 69]
 [ 2 62 73 36 91]]
result:
1275


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
print("matrix1:")
print(matrix1)

matrix2 = np.random.randint(1, 11, size=(4, 4))
print("matrix2:")
print(matrix2)

result = matrix1 - matrix2
print("result:")
print(result)

matrix1:
[[10  2  4  6]
 [ 5  9 10 10]
 [ 5 10 10  9]
 [ 3  3  4  7]]
matrix2:
[[1 2 6 5]
 [5 1 3 6]
 [1 4 5 4]
 [5 1 3 1]]
result:
[[ 9  0 -2  1]
 [ 0  8  7  4]
 [ 4  6  5  5]
 [-2  2  1  6]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
matrix = np.random.rand(3, 3)
print("matrix:")
print(matrix)

sums = np.sum(matrix, axis=1)
print("sums:")
print(sums)

result = sums.reshape(-1, 1)
print("result:")
print(result)

matrix:
[[0.56571885 0.28882979 0.44592254]
 [0.33446734 0.14778697 0.65310615]
 [0.97596248 0.18299497 0.95566756]]
sums:
[1.30047117 1.13536046 2.11462501]
result:
[[1.30047117]
 [1.13536046]
 [2.11462501]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [18]:
matrix = np.random.randint(1, 10, size=(3, 4))
print("matrix:")
print(matrix)

squared_matrix = np.square(matrix)
print("squared_matrix:")
print(squared_matrix)

matrix:
[[6 7 8 3]
 [1 4 4 2]
 [1 9 4 4]]
squared_matrix:
[[36 49 64  9]
 [ 1 16 16  4]
 [ 1 81 16 16]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
vector = np.random.randint(1, 51, size=4)
print("vector:")
print(vector)

sqrt_vector = np.sqrt(vector)
print("sqrt_vector:")
print(sqrt_vector)

vector:
[37 15 48 26]
sqrt_vector:
[6.08276253 3.87298335 6.92820323 5.09901951]
